name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        working-directory: cmd/server
        run: go build -o ida-assist-web.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ida-assist-web-windows
          path: cmd/server/ida-assist-web.exe
